kind: pipeline
type: docker
name: default

steps:
  - name: ✅ Test
    image: node
    commands:
      - yarn install
      - yarn test

  - name: 📦 Publish
    image: plugins/docker
    settings:
      repo: mauriceo/viewtube
      tags:
        - latest
        - '0.3.0'
        - '0.3'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: 🧪 Publish dev
    image: plugins/docker
    settings:
      repo: mauriceo/viewtube
      tags:
        - dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - dev
      event:
        - push

  - name: 🔔 Notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_bot_token
      to: -1001411660806
    when:
      branch:
        - master
      event:
        - push
      status:
        - success
        - failure

trigger:
  branch:
    - master
    - dev
