packages:
  - server
  - client
  - shared
  - tests
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  cypress: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
