packages:
  - server
  - client
  - shared
  - tests
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': set this to true or false
  '@swc/core': true
  cypress: true
  esbuild: true
  msgpackr-extract: set this to true or false
  sharp: true
  unrs-resolver: true
