import { AuthorThumbnailDto } from 'server/core/videos/dto/author-thumbnail.dto';
import { VideoBasicInfoDto } from 'server/core/videos/dto/video-basic-info.dto';
import { ChannelBasicInfoDto } from './channel-basic-info.dto';
import { ChannelLinkDto } from './channel-link.dto';

export class ChannelDto {
  author: string;
  authorId: string;
  authorUrl: string;
  authorUsername?: string;
  authorBanners: Array<{
    url: string;
    width: number;
    height: number;
  }>;
  authorThumbnails: Array<AuthorThumbnailDto>;

  subCount: number;
  totalViews: number;
  joined: number;

  paid: boolean;
  autoGenerated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: Array<string>;

  videoSections: Array<{
    title?: string;
    type: 'single' | 'multi';
    videos?: Array<VideoBasicInfoDto>;
    video?: VideoBasicInfoDto;
  }>;
  relatedChannels: Array<{ title: 'string'; channels: Array<ChannelBasicInfoDto> }>;
  channelLinks?: Array<ChannelLinkDto>;
}
