import { AuthorThumbnailDto } from 'server/core/videos/dto/author-thumbnail.dto';
import { VideoDto } from 'server/core/videos/dto/video.dto';
import { ChannelBasicInfoDto } from './channel-basic-info.dto';

export class ChannelDto {
  author: string;
  authorId: string;
  authorUrl: string;
  authorUsername?: string;
  authorBanners: Array<{
    url: string;
    width: number;
    height: number;
  }>;
  authorThumbnails: Array<AuthorThumbnailDto>;

  subCount: number;
  totalViews: number;
  joined: number;

  paid: boolean;
  autoGenerated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: Array<string>;

  latestVideos: Array<VideoDto>;
  relatedChannels: Array<ChannelBasicInfoDto>;
}
