import { RecommendedVideoDto } from './recommended-video.dto';
import { AuthorThumbnailDto } from './author-thumbnail.dto';
import { ChapterDto } from './chapter.dto';
import { VTThumbnailDto } from 'server/mapper/dto/vt-thumbnail.dto';

export class VideoDto {
  type: string;
  title: string;
  videoId: string;
  videoThumbnails: Array<VTThumbnailDto>;
  storyboards: object;
  description: string;
  descriptionHtml: string;
  published: number;
  publishedText: string;
  keywords: Array<string>;
  viewCount: number;
  likeCount: number;
  paid: boolean;
  premium: boolean;
  isFamilyFriendly: boolean;
  allowedRegions: Array<string>;
  genre: string;
  genreUrl: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: Array<AuthorThumbnailDto>;
  authorVerified: boolean;
  subCount: number;
  lengthSeconds: number;
  allowRatings: boolean;
  rating: number;
  isListed: boolean;
  liveNow: boolean;
  isUpcoming: boolean;
  adaptiveFormats: Array<any>;
  legacyFormats: Array<any>;
  chapters?: Array<ChapterDto>;
  captions: any;
  recommendedVideos: Array<RecommendedVideoDto>;
  dashManifest?: string;
}
